//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_Work.Language {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Module_Work.Language.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Актер.
        /// </summary>
        internal static string Actor {
            get {
                return ResourceManager.GetString("Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сельское хозяйство.
        /// </summary>
        internal static string Agriculture {
            get {
                return ResourceManager.GetString("Agriculture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Агроном.
        /// </summary>
        internal static string Agronomist {
            get {
                return ResourceManager.GetString("Agronomist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аниматор.
        /// </summary>
        internal static string Animator {
            get {
                return ResourceManager.GetString("Animator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Архитектор.
        /// </summary>
        internal static string Architect {
            get {
                return ResourceManager.GetString("Architect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бренд-дизайнер.
        /// </summary>
        internal static string BrandDesigner {
            get {
                return ResourceManager.GetString("BrandDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Животновод.
        /// </summary>
        internal static string Breeder {
            get {
                return ResourceManager.GetString("Breeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кинооператор.
        /// </summary>
        internal static string Cameraman {
            get {
                return ResourceManager.GetString("Cameraman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дирижер.
        /// </summary>
        internal static string Conductor {
            get {
                return ResourceManager.GetString("Conductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Творческие.
        /// </summary>
        internal static string Creative {
            get {
                return ResourceManager.GetString("Creative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критик.
        /// </summary>
        internal static string Critic {
            get {
                return ResourceManager.GetString("Critic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дизайнер.
        /// </summary>
        internal static string Designer {
            get {
                return ResourceManager.GetString("Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диджей.
        /// </summary>
        internal static string DJ {
            get {
                return ResourceManager.GetString("DJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фермер.
        /// </summary>
        internal static string Farmer {
            get {
                return ResourceManager.GetString("Farmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дизайнер-модельер.
        /// </summary>
        internal static string FashionDesigner {
            get {
                return ResourceManager.GetString("FashionDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фотомодель.
        /// </summary>
        internal static string FashionModel {
            get {
                return ResourceManager.GetString("FashionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Садовник.
        /// </summary>
        internal static string Gardener {
            get {
                return ResourceManager.GetString("Gardener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Охотник.
        /// </summary>
        internal static string Hunter {
            get {
                return ResourceManager.GetString("Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иллюстратор.
        /// </summary>
        internal static string Illustrator {
            get {
                return ResourceManager.GetString("Illustrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ювелир.
        /// </summary>
        internal static string Jeweler {
            get {
                return ResourceManager.GetString("Jeweler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мультипликатор.
        /// </summary>
        internal static string Multiplier {
            get {
                return ResourceManager.GetString("Multiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фотограф.
        /// </summary>
        internal static string Photographer {
            get {
                return ResourceManager.GetString("Photographer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режиссер.
        /// </summary>
        internal static string Producer {
            get {
                return ResourceManager.GetString("Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Киномеханик.
        /// </summary>
        internal static string Projectionist {
            get {
                return ResourceManager.GetString("Projectionist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реставратор.
        /// </summary>
        internal static string Restorer {
            get {
                return ResourceManager.GetString("Restorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сценарист.
        /// </summary>
        internal static string Screenwriter {
            get {
                return ResourceManager.GetString("Screenwriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звукорежиссер.
        /// </summary>
        internal static string SoundProducer {
            get {
                return ResourceManager.GetString("SoundProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каскадер.
        /// </summary>
        internal static string Stuntman {
            get {
                return ResourceManager.GetString("Stuntman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стилист.
        /// </summary>
        internal static string Stylist {
            get {
                return ResourceManager.GetString("Stylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Татуировщик.
        /// </summary>
        internal static string TattooArtist {
            get {
                return ResourceManager.GetString("TattooArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тракторист.
        /// </summary>
        internal static string TractorDriver {
            get {
                return ResourceManager.GetString("TractorDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переводчик.
        /// </summary>
        internal static string Translator {
            get {
                return ResourceManager.GetString("Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ветеринар.
        /// </summary>
        internal static string Veterinarian {
            get {
                return ResourceManager.GetString("Veterinarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Писатель.
        /// </summary>
        internal static string Writer {
            get {
                return ResourceManager.GetString("Writer", resourceCulture);
            }
        }
    }
}
